# vim: syntax=python tabstop=4 expandtab
# coding: utf-8

__author__ = "Jonas A"
__copyright__ = "Copyright 2021, Jonas A"
__email__ = "jonas.almlof@igp.uu.se"
__license__ = "GPL-3"


include: "rules/common.smk"
include: "rules/result_files.smk"

rule all:
    input:
        unpack(compile_output_list),

report: "report/workflow.rst"

import os
def get_module_snake_file(config, repo, path, tag):
    if 'hydra_local_path' in config:
        LocalGitFil(os.path.join(config['hydra_local_path'], repo), path=path, tag=tag)
    else:
        github(repo, path=path, tag=tag)
    
module prealignment:
   snakefile: get_module_snake_file(config, "hydra-genetics/prealignment", path="workflow/Snakefile", tag="develop")
   config: config

use rule * from prealignment as prealignment_*

module alignment:
   snakefile: get_module_snake_file(config, "hydra-genetics/alignment", path="workflow/Snakefile", tag="develop")
   config: config

use rule * from alignment as alignment_*

module snv_indels:
   snakefile: get_module_snake_file(config, "hydra-genetics/snv_indels", path="workflow/Snakefile", tag="develop")
   config: config

use rule * from snv_indels as snv_indels_*

module annotation:
   snakefile: get_module_snake_file(config, "hydra-genetics/annotation", path="workflow/Snakefile", tag="develop")
   config: config

use rule * from annotation as annotation_*

module filtering:
   snakefile: get_module_snake_file(config, "hydra-genetics/filtering", path="workflow/Snakefile", tag="develop")
   config: config

use rule * from filtering as filtering_*

module qc:
   snakefile: get_module_snake_file(config, "hydra-genetics/qc", path="workflow/Snakefile", tag="develop")
   config: config

use rule * from qc as qc_*

module biomarker:
   snakefile: get_module_snake_file(config, "hydra-genetics/biomarker", path="workflow/Snakefile", tag="develop")
   config: config

use rule * from biomarker as biomarker_*

module fusions:
   snakefile: get_module_snake_file(config, "hydra-genetics/fusions", path="workflow/Snakefile", tag="develop")
   config: config

use rule * from fusions as fusions_*

module cnv_sv:
   snakefile: get_module_snake_file(config, "hydra-genetics/cnv_sv", path="workflow/Snakefile", tag="develop")
   config: config

use rule * from cnv_sv as cnv_sv_*
