title: "Clinical Genomics MultiQC Report"
subtitle: "Reference used: GRCh37"
intro_text: "The MultiQC RNA report summarise analysis results from GMS560 panel data that been analysed by the Twist Solid pipeline (https://github.com/genomic-medicine-sweden/Twist_Solid)."

report_header_info:
  - Contact E-mail: !ENV "${NAME:igp-klinsek-bioinfo}@${DOMAIN:lists.uu.se}"
  - Application Type: "Bioinformatic analysis of GMS560 panel for solid cancers"

show_analysis_paths: True


#decimalPoint_format: ','
extra_fn_clean_exts: ##from this until end
    - '.duplication_metrics'
    - '.HsMetrics'
    - '.alignment_summary_metrics'
    - type: regex_keep
      pattern: '[0-9A-Z-]+'
#extra_fn_clean_trim:   #if found in beginning or end
#fn_ignore_dirs:
#fn_ignore_files:

use_filename_as_sample_name:
  - picard/hsmetrics
  - picard/alignment_metrics

custom_content:
  order:
    - qc-stats
    - fastqc
    - fastp
    - samtools
    - picard

table_columns_visible:
  "Picard: HsMetrics":
    FOLD_ENRICHMENT: False
    PCT_TARGET_BASES_30X: False
  "Picard: InsertSizeMetrics":
    summed_median: False
    summed_mean: False
  "Picard: Mark Duplicates":
    PERCENT_DUPLICATION: True
  "Samtools: stats":
    error_rate: False
    non-primary_alignments: False
    reads_mapped: True
    reads_mapped_percent: True
    reads_properly_paired_percent: False
    reads_MQ0_percent: False
    raw_total_sequences: False
  FastQC:
    percent_duplicates: False
    percent_gc: False
    avg_sequence_length: False
    percent_fails: False
    total_sequences: False

multiqc_cgs:
  "Samtools: stats":
    reads_mapped:
      title: "M Aligned reads"
      description: "Number of million reads in bam from Samtools stats"
      format: "{:.1f}"
      shared_key: "read_count"
  "Picard: Mark Duplicates":
    PERCENT_DUPLICATION:
      title: "Duplicates [%]"
      description: "Duplicates [%] from Picard stats (MarkDuplicates)"
      min: 0
      max: 0.4
      scale: "RdYlGn-rev"
      format: "{:.1%}"
  "Picard: HsMetrics":
    PCT_SELECTED_BASES:
      title: "Bases on target [%]"
      description: "Bases on target [%] from Picard"
      min: 0.5
      max: 1.0
      scale: "RdYlGn"
      format: "{:.1%}"
    PCT_USABLE_BASES_ON_TARGET:
      title: "Usable bases [%]"
      description: "Bases aligned, on target, and dedup [%] from Picard"
      min: 0.1
      max: 0.7
      scale: "RdYlGn"
      format: "{:.1%}"
    PCT_TARGET_BASES_100X:
      title: "Target bases over 100X [%]"
      description: "Target bases over 100X [%] from Picard"
      min: 0.5
      max: 1.0
      scale: "RdYlGn"
      format: "{:.1%}"
    MEAN_TARGET_COVERAGE:
      title: "Mean target coverage"
      description: "Mean target coverage from picard"
      format: "{:.1f}"
    MEDIAN_TARGET_COVERAGE:
      title: "Median target coverage"
      description: "Median target coverage from picard"
      format: "{:.1f}"
    AT_DROPOUT:
      title: "AT-dropout [%]"
      description: "AT-dropout [%] from Picard"
      min: 0
      max: 1
      scale: "RdYlGn-rev"
      format: "{:.3f}"
    GC_DROPOUT:
      title: "GC-dropout [%]"
      description: "GC-dropout [%] from Picard"
      min: 0
      max: 1
      scale: "RdYlGn-rev"
      format: "{:.3f}"
    ZERO_CVG_TARGETS_PCT:
      title: "Target bases with zero coverage [%]"
      description: "Target bases with zero coverage [%] from Picard"
      min: 0
      max: 0.1
      scale: "RdYlGn-rev"
      format: "{:.2%}"
    FOLD_80_BASE_PENALTY:
      title: "FOLD-80"
      description: "FOLD-80 penalty from picard"
      min: 0
      max: 10
      scale: "RdYlGn-rev"
      format: "{:.1f}"

table_columns_placement:
  "Samtools: stats":
    reads_mapped: 900
    reads_mapped_percent: 910
  "Picard: Mark Duplicates":
    PERCENT_DUPLICATION: 920
  "Picard: HsMetrics":
    PCT_SELECTED_BASES: 930
    PCT_USABLE_BASES_ON_TARGET: 940
    PCT_TARGET_BASES_100X: 950
    MEAN_TARGET_COVERAGE: 960
    MEDIAN_TARGET_COVERAGE: 970
    AT_DROPOUT: 1000
    GC_DROPOUT: 1010
    ZERO_CVG_TARGETS_PCT: 1020
    FOLD_80_BASE_PENALTY: 1030
    
