jobs: 100
keep-going: True
restart-times: 2
rerun-incomplete: True
use-singularity: True
configfiles: ["config/config.yaml", "config/config.data.hg19.yaml", "config/config.data.ctdna.hg19.yaml"]
#singularity-args: "-e --cleanenv -B /projects -B /data -B /beegfs-storage" #Locally dependent arguments for singularities
#singularity-prefix: "/projects/wp4/nobackup/singularity_cache/" #Local path to the singularity cache
drmaa: " -A wp1 -N 1-1 -t {resources.time} -n {resources.threads} --mem={resources.mem_mb} --mem-per-cpu={resources.mem_per_cpu} --mem-per-cpu={resources.mem_per_cpu} --partition={resources.partition} -J {rule} -e slurm_out/{rule}_%j.err -o slurm_out/{rule}_%j.out"
drmaa-log-dir: "slurm_out"
default-resources: [threads=1, time="04:00:00", partition="low", mem_mb="3074", mem_per_cpu="3074"]
