filters:
  observations:
    description: "Demand at least 10 observations"
    expression: "(INFO:AO < 10)"
    soft_filter: "False"
  af:
    description: "Hard filter ITD with less than 1% frequency"
    expression: "(INFO:AF < 0.01)"
    soft_filter: "False"
  dp:
    description: "Demand at least 100 coverage"
    expression: "(INFO:DP < 100)"
    soft_filter: "False"
