filters:
  intron:
    description: "Soft filter intronic variants"
    expression: "(exist[intron_variant, VEP:Consequence] and !exist[splice, VEP:Consequence] and VEP:SYMBOL != MET and VEP:SYMBOL != TERT and !exist[COSV[0-9]+, VEP:Existing_variation])"
    soft_filter_flag: "Intronic"
    soft_filter: "True"
  vaf:
    description: "Soft filter variants with low vaf (AF lower than 0.01)"
    expression: "(FORMAT:AF:0 < 0.01)"
    soft_filter_flag: "AF_lt_0.01"
    soft_filter: "True"
  artifacts:
    description: "Soft filter variants found in more than 3 normal samples"
    expression: "((INFO:Artifact:0 > 3 and INFO:ArtifactNrSD:0 < 5) or (INFO:Artifact:1 > 3 and INFO:ArtifactNrSD:1 < 5))"
    soft_filter_flag: "Artifact_gt_3"
    soft_filter: "True"
  background:
    description: "Soft filter position with where backgound distribution overlaps variant (lower than 4 SD from median)"
    expression: "(INFO:PositionNrSD < 4 and !exist[1-hotspot, INFO:Hotspot])"
    soft_filter_flag: "Background_lt_4"
    soft_filter: "True"
  germline:
    description: "Soft filter germline SNVs based on GnomAD exon"
    expression: "(VEP:gnomADe_AF > 0.005)"
    soft_filter_flag: "Germline"
    soft_filter: "True"
  ad:
    description: "Soft filter variants with few observations (AD lower than 20)"
    expression: "(FORMAT:AD:1 < 20 and !exist[1-hotspot, INFO:Hotspot] and VEP:SYMBOL != TERT)"
    soft_filter_flag: "AD_lt_20"
    soft_filter: "True"
  ad_hotspot:
    description: "Soft filter hotspot variants with few observations (AD lower than 10)"
    expression: "(FORMAT:AD:1 < 10 and exist[1-hotspot, INFO:Hotspot] and VEP:SYMBOL != TERT)"
    soft_filter_flag: "AD_HS_lt_10"
    soft_filter: "True"
  ad_TERT:
    description: "Soft filter TERT variants with few observations (AD lower than 4)"
    expression: "(FORMAT:AD:1 < 4 and exist[1-hotspot, INFO:Hotspot] and VEP:SYMBOL = TERT)"
    soft_filter_flag: "AD_TERT_lt_4"
    soft_filter: "True"
